### ISSUE TITLE
When I toggle Between typing component it is not working

### ISSUE THREAD

**Issue by karanshrm44** [adamjking3/react-typing-animation#27] opened 2018-10-12 17:39 UTC
k

**Comment by karanshrm44** [comment] 2018-10-12 17:41
Why it is not showing typing component i don't know, Just check the codesandbox

**Comment by adamjking3** [comment] 2018-12-08 05:54
Hey @karanshrm44, I'm going to close this because I'm not sure what the problem is. If you want to explain the problem in more detail and submit instructions on how to reproduce it, I will re-open the issue.

**Closed by adamjking3** 2018-12-08 05:54 UTC
